channels:
- ioos
dependencies:
- protobuf=3.0.0=py27_0
- openssl=1.0.2h=1
- pip=8.1.2=py27_0
- python=2.7.11=0
- readline=6.2=2
- setuptools=23.0.0=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
    - protobuf==3.1.0.post1
    - sphinx==1.5.1
    - graphviz
